version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build: .
    environment:
      CONNECTION_STRING: postgresql://postgres:${DB_PASSWORD}@postgres:5432/sprocket_factory
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
