name: Deploy to Goggle App Engine (GAE)

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '20.13.1'

      - name: Install dependencies
        run: npm install --only-production

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure environment variables
        run: |
          echo "env_variables:" >> app.yaml
          echo "  DB_USER: '${{ secrets.DB_USER }}'" >> app.yaml
          echo "  DB_PASSWORD: '${{ secrets.DB_PASSWORD }}'" >> app.yaml
          echo "  DB_HOST: '${{ secrets.DB_HOST }}'" >> app.yaml
          echo "  DB_PORT: '${{ secrets.DB_PORT }}'" >> app.yaml
          echo "  DB_NAME: '${{ secrets.DB_NAME }}'" >> app.yaml
          echo "  SPROCKETS_STRATEGY: '${{ secrets.SPROCKETS_STRATEGY }}'" >> app.yaml
          echo "  FACTORIES_STRAREGY: '${{ secrets.FACTORIES_STRAREGY }}'" >> app.yaml

      - name: Deploy to Google App Engine
        run: |
          gcloud app deploy app.yaml --quiet
